remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Atelier de Código
description: Un lugar para aprender a programar de forma artesanal
copyright: '@ {year} Noelia Stetie y Macarena Quiroga'

defaultContentLanguage: es

